# Generated by Django 4.1.6 on 2023-06-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('descritpion', models.TextField(blank=True, max_length=2000)),
            ],
        ),
    ]
