# Generated by Django 4.2 on 2023-04-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('reservation_slot', models.SmallIntegerField(default=10)),
            ],
            options={
                'unique_together': {('name', 'date')},
            },
        ),
    ]
