# Generated by Django 4.2 on 2023-04-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('date', 'reservation_slot')},
        ),
    ]
