# Generated by Django 4.2.5 on 2023-10-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0003_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': [('can_mark_returned', 'Set book as returned')]},
        ),
    ]
