# Generated by Django 4.1.7 on 2023-03-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inventory',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
